### ISSUE TITLE
change enum34 dependency to enum-compat

### ISSUE THREAD

**Issue by haakenlid** [miki725/django-url-filter#43]
I'm using python 3.6 and after installing django-url-filter my test runner is broken. Turns out that it's caused by the enum34 package which is not compatible with the standard library enum, which is used by other standard library modules such as `re`. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 18, in <module>
    import traceback
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/local/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```
It seems that there is a package that solves this. It will install enum34 only on versions < 3.4, to avoid messing with the standard library enum in current versions of python 3.

https://pypi.python.org/pypi/enum-compat

**Comment by haakenlid** [comment]
Fixed with merge.
