### ISSUE TITLE
How to specify a url filter for related models with multiple levels ?

### ISSUE THREAD

**Issue by selimt** [miki725/django-url-filter#60]
Hi, I can use the url-filter manually for related models multiple levels deep like this:

```
from django.http import QueryDict
from url_filter.filtersets import ModelFilterSet
class FilterSet(ModelFilterSet):
     class Meta(object):
         model = TransferRequest

>>> q = QueryDict('transfer_job__transfer_session__priority=1')
>>> fs = FilterSet(data=q, queryset=TransferRequest.objects.all())
>>> fs.filter()
<QuerySet [<TransferRequest: ffdf29cb-1de7-4553-9c8b-b476a0d9d9f0>, ...
```

but if I have a model view set like this:

```
class TransferRequestViewSet(QueryOrderableViewSetMixin, viewsets.ModelViewSet):
    queryset = TransferRequest.objects.all()
    serializer_class = TransferRequestSerializer
    filter_backends = [DjangoFilterBackend]
    filter_fields = ['source_studio', 'destination_studio', 'requester_studio', 'user', 'created',
                     'priority', 'options', 'status', 'paths', 'guid',
                     # relation names
                     "transfer_job", "transfer_job__transfer_session"]
```

and I enter a URL like this:
```
http://localhost/api/requests/?transfer_job__transfer_session__priority=1
```

I get the following error:

```
2018-06-07T00:16:21.404012283Z KeyError: 'transfer_job__transfer_session'
2018-06-07T00:16:21.404015892Z 
2018-06-07T00:16:21.404019373Z During handling of the above exception, another exception occurred:
2018-06-07T00:16:21.404022912Z 
2018-06-07T00:16:21.404026226Z Traceback (most recent call last):
2018-06-07T00:16:21.404029726Z   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
2018-06-07T00:16:21.404033418Z     response = get_response(request)
2018-06-07T00:16:21.404048822Z   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
2018-06-07T00:16:21.404052804Z     response = self.process_exception_by_middleware(e, request)
2018-06-07T00:16:21.404055994Z   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
2018-06-07T00:16:21.404059390Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-06-07T00:16:21.404062545Z   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
2018-06-07T00:16:21.404065945Z     return view_func(*args, **kwargs)
2018-06-07T00:16:21.404068985Z   File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
2018-06-07T00:16:21.404072336Z     return self.dispatch(request, *args, **kwargs)
2018-06-07T00:16:21.404075373Z   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
2018-06-07T00:16:21.404078630Z     response = self.handle_exception(exc)
2018-06-07T00:16:21.404081677Z   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
2018-06-07T00:16:21.404085025Z     self.raise_uncaught_exception(exc)
2018-06-07T00:16:21.404088460Z   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
2018-06-07T00:16:21.404091759Z     response = handler(request, *args, **kwargs)
2018-06-07T00:16:21.404094827Z   File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
2018-06-07T00:16:21.404098214Z     queryset = self.filter_queryset(self.get_queryset())
2018-06-07T00:16:21.404101283Z   File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 152, in filter_queryset
2018-06-07T00:16:21.404104530Z     queryset = backend().filter_queryset(self.request, queryset, self)
2018-06-07T00:16:21.404108429Z   File "/usr/local/lib/python3.6/site-packages/url_filter/integrations/drf.py", line 160, in filter_queryset
2018-06-07T00:16:21.404111880Z     return _filter.filter()
2018-06-07T00:16:21.404115061Z   File "/usr/local/lib/python3.6/site-packages/url_filter/filtersets/base.py", line 324, in filter
2018-06-07T00:16:21.404118401Z     specs = self.get_specs()
2018-06-07T00:16:21.404121429Z   File "/usr/local/lib/python3.6/site-packages/url_filter/filtersets/base.py", line 358, in get_specs
2018-06-07T00:16:21.404124811Z     specs.append(self.get_spec(data))
2018-06-07T00:16:21.404127821Z   File "/usr/local/lib/python3.6/site-packages/url_filter/filtersets/base.py", line 400, in get_spec
2018-06-07T00:16:21.404131037Z     if name not in self.filters:
2018-06-07T00:16:21.404134085Z   File "/usr/local/lib/python3.6/site-packages/cached_property.py", line 35, in __get__
2018-06-07T00:16:21.404138102Z     value = obj.__dict__[self.func.__name__] = self.func(obj)
2018-06-07T00:16:21.404141194Z   File "/usr/local/lib/python3.6/site-packages/url_filter/filtersets/base.py", line 224, in filters
2018-06-07T00:16:21.404147396Z     filters = self.get_filters()
2018-06-07T00:16:21.404150516Z   File "/usr/local/lib/python3.6/site-packages/url_filter/filtersets/base.py", line 487, in get_filters
2018-06-07T00:16:21.404153786Z     _filter = self._build_filter(name, state)
2018-06-07T00:16:21.404156840Z   File "/usr/local/lib/python3.6/site-packages/url_filter/filtersets/django.py", line 93, in _build_filter
2018-06-07T00:16:21.404160186Z     field = self.Meta.model._meta.get_field(name)
2018-06-07T00:16:21.404163206Z   File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 619, in get_field
2018-06-07T00:16:21.404166434Z     raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
2018-06-07T00:16:21.404169750Z django.core.exceptions.FieldDoesNotExist: TransferRequest has no field named 'transfer_job__transfer_session'
```

Is there a special syntax for entering such filters ?

Thanks
-Selim

**Comment by miki725** [comment]
you cant specify nested filterset fields on parent filterset. you can overwrite the child filterset manually though if you need to or specify the relation name and child filterset will automatically be built. see https://django-url-filter.readthedocs.io/en/latest/usage.html#vanilla for an example.

**Comment by selimt** [comment]
Actually, once I removed the nested relation name from the filter_fields it magically worked:
```
http://localhost/api/requests/detail/?transfer_job__transfer_session__guid=677fdfab-ca21-4535-9959-a11d15952608
```

With just "transfer_job" relation name in filter_fields I could filter in the transfer_session model.

According to your suggestion would it be also possible to create a nested FilterSet and provide that as a value for the "filter_class" class variable under the ModelViewSet ?

**Comment by miki725** [comment]
no. you need to provide parent filterset to `ModelViewSet` since both models need to match. 

see previous docs link for an example how to customize child filterset if you need to. 

closing since issue seems to be resolved however feel free to reopen if you like.

**Comment by selimt** [comment]
Thank you!
